baseURL = "https://jaglima.github.io/"
languageCode = "en-us"
title = "Jesse Lima"
theme = "cactus"
copyright = "Jesse Lima" # cactus will use title if copyright is not set
disqusShortname = "disqus_N5UYfwWytN" # Used when comments is enabled. Cactus will use site title if not set
googleAnalytics = "G-0S4YSP929R"

# summaryLength = 4

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Archives"
url = "/posts"
weight = 2

[[menu.main]]
name = "About me"
url = "/about"
weight = 6

[[menu.main]]
name = "Essays"
url = "/essays"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  colortheme = "classic" # dark, light, white, or classic
  rss = false # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default

  # Home page settings
  description = "This is my personal blog where I write about work, technical topics, science, and related ideas."
  mainSection = "archives" # your main section
  showAllPostsOnHomePage = true # default
  postsOnHomePage = 100 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

[services]
  [services.disqus]
    shortname = 'disqus_N5UYfwWytN'

  [params.comments]
    enabled = true # non default
    engine = "disqus" # only disqus, utterances, and cactus_comments is supported

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/jaglima"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/jesseaglima/"
  [[params.social]]
    name = "email"
    link = "jesselima@protonmail.com"  # no need for "mailto:" in the head

[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1